project:
  type: website
  resources: 
    - assets/**
  output-dir: docs
  render: 
    - "*.qmd"
    - "lectures/**.qmd"
#    - "!lectures/Chapter05_Lecture**.qmd"
#    - "!lectures/Chapter06_Lecture**.qmd"

website:
  title: "Investments"
  site-url: "https://clb18.github.io/FIN-3440_Investments"
  repo-url: "https://github.com/clb18/FIN-3440_Investments"

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: CV
        href: cv.qmd

  sidebar:
    style: docked
    search: true
    contents:
      - section: "Lecture Notes"
        contents: 
          - text: "Ch 0 - Problems with Investment Theory"
            href: Lectures/Chapter00_Lecture.qmd
          - section: Elements of Investments
            contents:
              - text: "Ch 1 - Background and Issues"
                href: Lectures/Chapter01_Lecture.qmd
              - text: "Ch 2 - Asset Classes"
                href: Lectures/Chapter02_Lecture.qmd
              - text: "Ch 3 - How Securities Trade"
                href: Lectures/Chapter03_Lecture.qmd
              - text: "Ch 4 - Mutual Funds"
                href: Lectures/Chapter04_Lecture.qmd
        #- section: Portfolio Theory
          #contents:
              #- text: 
                #href:
      
format:
  html:
    code-fold: true
    code-summary: "Show/hide R code"
    theme: cosmo
    toc: true
    toc-location: left
    number-sections: true
    css: styles.css
    grid:
      sidebar-width: 275px
      body-width: 1200px
      margin-width: 0px
      gutter-width: 1.5rem