---
title: "Investments"
---

## Course overview

### Catalog Description

**Theory, concepts, and principles of investment decisions. Portfolio construction and management; investment media; fundamental and technical analysis; tools of investment analysis; psychological aspects of the market.**

### Syllabus Statement

This course will study financial markets and the relationship between risk and return. We will also examine the instruments used in the market and some of the valuation methods to adequately price those instruments. We will also discuss and apply our finding to develop and build a well-balanced portfolio.

Managerial Finance (FIN3430) is the only prerequisite for this course. This course, while an upper-level finance course, is at the same time an economics course. We will be looking at finance broadly, not just the calculations, but the decisions and the incentives behind the decisions that guide the financial markets.

## Important dates

-   **Mon, Jan 12** — First day of class
-   **Mon, Jan 19** — No class
-   **Mon-Fri, Mar 23-27** - Spring Break
-   **Mon, May 4** — Final exam

## Topics covered

-   coming soon...
